# Generated by Django 5.0.6 on 2024-09-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.RenameField(
            model_name='estados',
            old_name='estados',
            new_name='tipo',
        ),
    ]
