# Generated by Django 5.0.1 on 2024-09-23 18:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coberturas', '0003_coberturas_descripcion_coberturas_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('Naciemiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fechaEntrada', models.DateTimeField(default=datetime.datetime.now)),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coberturas.coberturas')),
            ],
            options={
                'verbose_name': ('paciente',),
                'verbose_name_plural': 'pacientes',
            },
        ),
    ]
