# Generated by Django 5.0.1 on 2024-09-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
    ]
