# Generated by Django 5.0.1 on 2024-09-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctores',
            old_name='apeliido',
            new_name='apellido',
        ),
    ]
