# Generated by Django 5.0.1 on 2024-09-25 16:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0002_rename_apeliido_doctores_apellido'),
        ('pacientes', '0002_alter_paciente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTurno', models.DateTimeField()),
                ('fechaSolicitud', models.DateField(default=datetime.datetime.now)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctores')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
