# Generated by Django 5.0.6 on 2024-09-30 20:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        ('lugares', '0001_initial'),
        ('pacientes', '0002_alter_paciente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTurno', models.DateTimeField()),
                ('fechaSolicitud', models.DateField(default=datetime.date.today)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctores')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.lugares')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
