# Generated by Django 5.0.6 on 2024-09-30 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
        ('estados', '0002_alter_estados_options_rename_estados_estados_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='estados.estados'),
        ),
    ]
