# Generated by Django 5.0.1 on 2024-09-29 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_alter_cita_doctor_alter_cita_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaSolicitud',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
