# Generated by Django 5.0.1 on 2024-09-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_alter_cita_fechasolicitud'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.lugares'),
        ),
    ]
