# Generated by Django 5.0.1 on 2024-09-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coberturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coberturas',
            options={'verbose_name': 'cobertura', 'verbose_name_plural': 'coberturas'},
        ),
    ]
