# Generated by Django 5.0.1 on 2024-09-20 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coberturas', '0002_alter_coberturas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coberturas',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coberturas',
            name='nombre',
            field=models.CharField(default=0.0003407387215483168, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coberturas',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
